name: "InferSharp-PR"

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: sudo apt-get update -y
  displayName: 'Initialize'

- task: Docker@2
  displayName: 'Build and test'
  inputs:
    command: build